=== jonimoreira/specs/xml2ccd/XML2CCD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:x2c="http://www.mlhim.org/xmlns/mlhim2/xml2ccd"
  targetNamespace="http://www.mlhim.org/xmlns/mlhim2/xml2ccd" version="2.4.4"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.0">

  <xs:element name="xml-to-ccd" type="x2c:xml-to-ccd"/>
  
  <xs:complexType name="xml-to-ccd">
    <xs:sequence>
      <xs:element name="version" minOccurs="1" maxOccurs="1" type="xs:string" fixed="2.4.4"/>
      <xs:element minOccurs="1" maxOccurs="1" name="ccd-def" type="x2c:ccd-def"/>
      <xs:element minOccurs="1" maxOccurs="1" ref="x2c:entry"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="ccd-def">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="description" type="xs:string" default="None provided by author."/>
      <xs:element name="subject" type="xs:string" default="None provided by author."/>
      <xs:element name="source" type="xs:string" default="None provided by author."/>
      <xs:element name="rights" type="xs:string" default="None provided by author."/>
      <xs:element name="relation" type="xs:string" default="None provided by author."/>
      <xs:element name="coverage" type="xs:string" default="None provided by author."/>
      <xs:element name="creator-name" type="xs:string"/>
      <xs:element name="creator-email" type="xs:string"/>
      <xs:element name="contributor">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="email" minOccurs="1" maxOccurs="1" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  
  <xs:element name="entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="entry-type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="admin"/>
              <xs:enumeration value="care"/>
              <xs:enumeration value="demog"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="entry-link" type="x2c:dvuri"/> <!-- entry-links = DvURI -->
        <xs:element maxOccurs="1" minOccurs="0" name="entry-audit"/>
        <xs:element maxOccurs="1" minOccurs="1" name="language" type="xs:language"/>
        <xs:element maxOccurs="1" minOccurs="1" name="encoding" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="1" name="entry-subject" type="x2c:party"/>  
        <xs:element maxOccurs="1" minOccurs="0" name="entry-provider" type="x2c:party"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="other-participations" type="x2c:participation"/>            
        <xs:element maxOccurs="1" minOccurs="0" name="protocol-id" type="x2c:dvidentifier"/>            
        <xs:element maxOccurs="1" minOccurs="0" name="current-state" type="xs:string"/>    
        <xs:element maxOccurs="1" minOccurs="0" name="workflow-id" type="x2c:dvuri"/>            
        <xs:element maxOccurs="1" minOccurs="0" name="attestation" type="x2c:attestation"/>    
        <xs:element maxOccurs="1" minOccurs="1" name="entry-data" type="x2c:cluster"/>    
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="cluster">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="data-name" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="resource-uri" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string"/>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="dv" type="x2c:dvany"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="cluster" type="x2c:cluster"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType abstract="true" name="dvany">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="data-name" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="resource-uri" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="dvuri">
    <xs:complexContent>
      <xs:extension base="x2c:dvany">
        <xs:sequence>
             <xs:element minOccurs="0" maxOccurs="1" name="relation" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="dvstring">
    <xs:complexContent>
      <xs:extension base="x2c:dvany">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="enumerations" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="0" maxOccurs="1" name="pattern" type="xs:string"/> <!-- regexp -->          
          <xs:element minOccurs="0" maxOccurs="1" name="length" type="xs:decimal"/>                    
          <xs:element minOccurs="0" maxOccurs="1" name="min-length" type="xs:decimal"/>                    
          <xs:element minOccurs="0" maxOccurs="1" name="max-length" type="xs:decimal"/>                    
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="dvcodedstring">
    <xs:complexContent>
      <xs:extension base="x2c:dvstring">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="abbrev" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="1" maxOccurs="1" name="name" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="1" maxOccurs="1" name="version" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="1" maxOccurs="1" name="code" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  

  <xs:complexType name="dvidentifier">
    <xs:complexContent>
      <xs:extension base="x2c:dvstring">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="id-name" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="1" maxOccurs="1" name="issuer" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="1" maxOccurs="1" name="assignor" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->                    
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="dvboolean">
    <xs:complexContent>
      <xs:extension base="x2c:dvany">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="trues" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
          <xs:element minOccurs="1" maxOccurs="1" name="falses" type="xs:string"/> <!-- semi-colon separated list used for enumerations -->          
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  





  <xs:complexType name="attestation">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="data-name" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="resource-uri" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string"/>
      
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="party">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="data-name" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="resource-uri" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string"/>
      
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="participation">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="data-name" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="resource-uri" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string"/>
      
    </xs:sequence>
  </xs:complexType>


  <!--
  
  <xs:element name="pcttype">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="DvString"/>
        <xs:enumeration value="DvCount"/>        
        <xs:enumeration value="DvQuantity"/>        
        <xs:enumeration value="DvOrdinal"/>        
        <xs:enumeration value="DvBoolean"/>        
        <xs:enumeration value="DvString-enumerated"/>        
        <xs:enumeration value="DvTemporal-date"/>        
        <xs:enumeration value="DvTemporal-datetime"/>        
        <xs:enumeration value="DvTemporal-time"/>        
        <xs:enumeration value="DvURI"/>        
        <xs:enumeration value="DvMedia"/>        
        <xs:enumeration value="DvParsable"/>        
      </xs:restriction>
    </xs:simpleType>
  </xs:element>  
  -->
  
</xs:schema>

=== jonimoreira/specs/xml2ccd/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<x2c:xml-to-ccd xmlns:x2c="http://www.mlhim.org/xmlns/mlhim2/xml2ccd"
 xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.mlhim.org/xmlns/mlhim2/xml2ccd file:/home/tim/MLHIM/git/specs/xml2ccd/XML2CCD.xsd">
  <version>2.4.4</version>
  <ccd-def>
    <title>Uk960akofYDUbL7</title>
    <description>None provided by author.</description>
    <subject>None provided by author.</subject>
    <source>None provided by author.</source>
    <rights>None provided by author.</rights>
    <relation>None provided by author.</relation>
    <coverage>None provided by author.</coverage>
    <creator-name>TLXlJOXh9Rt7zeTPW6bWJeNibew8s</creator-name>
    <creator-email>uKeA</creator-email>
    <contributor>
      <name>SOj2rd1FsRKG3eUUwb2jQ6ZZTCB</name>
      <email>lPXQNFLv-APQ</email>
    </contributor>
  </ccd-def>
  <x2c:entry>
    <entry-type>demog</entry-type>
    <entry-link>
      <data-name>KDKLHd</data-name>
      <resource-uri>FnTH41EZCfdv4bfdf.UG3-BZ</resource-uri>
      <description>UrUT3_MRQHY</description>
      <relation>eF5CMbKNmmDHiOKCspmYAb9</relation>
    </entry-link>
    <entry-link>
      <data-name>vHBWGrB9Eju7x4NJtEdh9f</data-name>
      <resource-uri>RVDt</resource-uri>
      <description>m</description>
      <relation>sZ1myb</relation>
    </entry-link>
    <entry-audit>
    </entry-audit>
    <language>ja-JP</language>
    <encoding>qciaiHE1LgprXeJ1MZ</encoding>
    <entry-subject>
      <data-name>H1A</data-name>
      <resource-uri>s6L9n</resource-uri>
      <description>mK0Qbyvo0O6po0DFKsopNBBhQXF</description>
    </entry-subject>
    <entry-provider>
      <data-name>Xv</data-name>
      <resource-uri>vwGbWWbwSm-8WYfgh2qY808FJB2och</resource-uri>
      <description>A8ScPlXY6x4cqcxC7F5geX</description>
    </entry-provider>
    <other-participations>
      <data-name>kl3d5xg._ZrFsr2C0Jr</data-name>
      <resource-uri>Aku6dOv3EpMgHW1o48JWMhwn</resource-uri>
      <description>B</description>
    </other-participations>
    <other-participations>
      <data-name>J1IAriciUUDPb3BgFAvOZHZI1P.</data-name>
      <resource-uri>Hm.h9szsL3p2FgBk2OhfvcKt-</resource-uri>
      <description>WKBGeQhW5LOyvmWHqkqbLU6A-jW</description>
    </other-participations>
    <protocol-id>
      <data-name>fRQBHpi</data-name>
      <resource-uri>sqU8Oh-Dqcb7LNWxJK.cK</resource-uri>
      <description>bWPqKX</description>
      <id-name>dW_hBilvB-z5G</id-name>
      <issuer>glNOF</issuer>
      <assignor>fIdjQpi_ab8ujyVrnM</assignor>
    </protocol-id>
    <current-state>cOboVQy</current-state>
    <workflow-id>
      <data-name>t5JI53Nk8zW0-sx0jni</data-name>
      <resource-uri>qkE9bz8ukK25oqsrcX8</resource-uri>
      <description>HsqGH2L</description>
      <relation>MKkfm</relation>
    </workflow-id>
    <attestation>
      <data-name>n._vfsIDnx.</data-name>
      <resource-uri>Z9D3xh1lPqehy2DVqaabZJPmj</resource-uri>
      <description>OsOHGuZmLq6M_zPlZx7Ztgng</description>
    </attestation>
    <entry-data>
      <data-name>Wv24o0ytk</data-name>
      <resource-uri>zWUuuTsv</resource-uri>
      <description>J.4FIZs</description>
      <dv xsi:type="x2c:dvuri">
        <data-name>g</data-name>
        <resource-uri>oZ2uoXV7mm42fWAYq.X0DpZt6CH</resource-uri>
        <description>Cfzbh</description>
        <relation>ABzg8</relation>
      </dv>
      <dv xsi:type="x2c:dvuri">
        <data-name>rN5GphXNBpNjl</data-name>
        <resource-uri>eXH41j9ZmSMZJcFaNPot-D</resource-uri>
        <description>WnXiG3j8lC4cJqYVyVW9R5TA5h</description>
        <relation>IGTzy0ul2814fNTO4_-0</relation>
      </dv>
    </entry-data>
  </x2c:entry>
</x2c:xml-to-ccd>
